apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeds-app
  labels:
    app: feeds-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: mabangura/udagram-api-feed
        ports:
        - containerPort: 80
        env:
        - name: POSTGRESS_USERNAME
          value: "postgres"
        - name: POSTGRESS_PASSWORD
          value: "Zara2012"
        - name: POSTGRESS_DATABASE
          value: "postgres"
        - name: POSTGRESS_HOST
          value: "database-1.crttnlui3p8l.us-east-1.rds.amazonaws.com"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_MEDIA_BUCKET
          value: "cloud-dev-s3"
        - name: JWT_SECRET
          value: "testing"