language: generic

services:
  - docker

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy

  - docker tag udagram-api-feed mabangura/udagram-api-feed:v1
  - docker tag udagram-api-user mabangura/udagram-api-user:v1
  - docker tag udagram-frontend mabangura/udagram-frontend:v1
  - docker tag udagram-reverseproxy mabangura/udagram-reverseproxy:v1

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mabangura/udagram-api-feed:v1
  - docker push mabangura/udagram-api-user:v1
  - docker push mabangura/udagram-frontend:v1
  - docker push mabangura/reverseproxy:v1